"""empty message

Revision ID: 05c4a6578130
Revises: 95c4a000b5a8
Create Date: 2018-10-24 14:18:15.789261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05c4a6578130'
down_revision = '95c4a000b5a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hall',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('h_address_id', sa.Integer(), nullable=True),
    sa.Column('h_num', sa.Integer(), nullable=True),
    sa.Column('h_seats', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['h_address_id'], ['cinema_address.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('h_num')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hall')
    # ### end Alembic commands ###
