"""empty message

Revision ID: 3398864793df
Revises: 05c4a6578130
Create Date: 2018-10-24 14:48:07.588011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3398864793df'
down_revision = '05c4a6578130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hall_movie',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('h_movie_id', sa.Integer(), nullable=True),
    sa.Column('h_hall_id', sa.Integer(), nullable=True),
    sa.Column('h_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['h_hall_id'], ['hall.id'], ),
    sa.ForeignKeyConstraint(['h_movie_id'], ['movies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hall_movie')
    # ### end Alembic commands ###
